<<<<<<< HEAD
# Site settings
title: SeanAbu 
header-img: img/home-bg.jpg
email: seanabu.wilson@gmail.com
description: "Just a few posts to share my work as a data scientist with you."
baseurl: ""
url: "www.seanabu.com"
linkedin_username: SeanAbu
github_username:  SeanAbu


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
=======
# Site settings
title: SeanAbu 
header-img: img/home-bg.jpg
email: seanabu.wilson@gmail.com
description: "Just a few posts to share my work as a data scientist with you."
baseurl: ""
url: "www.seanabu.com"
linkedin_username: SeanAbu
github_username:  SeanAbu


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
>>>>>>> c4155d1ef8f3f4e37872b46a28f1f903cf531dfd
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]